### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by harmenwassenaar** [sybrenjansen/mpire#123]
I got an exception message during unittests of a Project we use mpire in

```
Exception in thread Thread-678 (_timeout_handler):
Traceback (most recent call last):
  File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/harmen.local/Projects/venvs/adg310/lib64/python3.10/site-packages/mpire/pool.py", line 343, in _timeout_handler
    and all(job._timeout is None for job in self._cache.values())
  File "/home/harmen.local/Projects/venvs/adg310/lib64/python3.10/site-packages/mpire/pool.py", line 343, in <genexpr>
    and all(job._timeout is None for job in self._cache.values())
RuntimeError: dictionary changed size during iteration
```

This is with the latest version of mpire (2.10.0).
It wasn't a fatal exception, so I guess it's caught and handled internally, but maybe it's worth fixing properly. It's not a frequent issue either (I don't recall seeing it before), so it might be hard to reproduce reliably.

**Comment by sybrenjansen** [comment]
Whenever a task is finished it's directly removed from the cache dictionary. When the timeout handler is also active and looping over the items you get this error.

I added the check in the latest version, but I guess I will remove it again to avoid this error. In hindsight I don't think the penalty is that big if the `if` is not there.

**Comment by sybrenjansen** [comment]
Good point, that is indeed better. And slightly out of date doesn't matter that much imo
