### ISSUE TITLE
Unable to import in Windows

### ISSUE THREAD

**Issue by huntfx** [sybrenjansen/mpire#7]
Saw you wrote this, turned out to be quite true:

> Disclaimer: it could be that MPIRE can’t be imported on systems without fork. If so, let me know by submitting an issue on GitHub.

Here's my traceback:

```
Traceback (most recent call last):
  File "", line 1, in <module>
    from mpire import WorkerPool
  File "C:\Users\Peter\AppData\Roaming\Python\Python39\site-packages\mpire\__init__.py", line 4, in <module>
    from mpire.pool import WorkerPool
  File "C:\Users\Peter\AppData\Roaming\Python\Python39\site-packages\mpire\pool.py", line 17, in <module>
    from mpire.comms import WorkerComms
  File "C:\Users\Peter\AppData\Roaming\Python\Python39\site-packages\mpire\comms.py", line 8, in <module>
    from mpire.context import MP_CONTEXTS
  File "C:\Users\Peter\AppData\Roaming\Python\Python39\site-packages\mpire\context.py", line 25, in <module>
    MP_CONTEXTS = {'mp': {'fork': mp.get_context('fork'),
  File "C:\Program Files\Python39\lib\multiprocessing\context.py", line 239, in get_context
    return super().get_context(method)
  File "C:\Program Files\Python39\lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'
```

**Comment by sybrenjansen** [comment]
Windows support is now available!
