### ISSUE TITLE
Depth of data slicing wrong

### ISSUE THREAD

**Issue by kimrojas** [sybrenjansen/mpire#80]
Hi 

Edit: Added error message

I'd like to ask for some advice regarding the behavior of mpire. 
I have a list of `Atoms` objects: `data = [Atoms0, Atoms1, Atoms2, Atoms3, ...]` 
This Atoms0 = [Atoms0[0], Atoms0[1], Atoms0[2], ... ]
So `data` is some sort of nested list of objects.
However, when I use the MPIRE package (as a drop-in replacement for multiprocessing) the slicing of data is wrong. 
I expect for the workers to behave like:

```
worker 0 <- function(Atoms0)
worker 1 <- function(Atoms1)
worker 2 <- function(Atoms2)
...
```
Meanings the depth of slicing is 1 (the primary list)

Instead the behavior (based on a nice error handling):
```
worker 0 <- function(Atoms0[0], Atoms0[1], Atoms0[2], Atoms0[3], ...)
worker 1 <- function(Atoms1[0], Atoms1[1], Atoms1[2], Atoms1[3], ...)
worker 2 <- function(Atoms2[0], Atoms2[1], Atoms2[2], Atoms2[3], ...)
...
```
Which suggest that the input arguments being used is of depth=2 (secondary list)

I am not sure what is triggering this behavior. 
My current workaround is to iterate over index numbers instead of the list objects like:
```
def task(data_index):
    return self.time_consuming_function(self.data[data_index])
with WorkerPool(n_jobs=5) as pool:
    self.results = pool.map(task, range(len(self.data)))
```
This workaround works properly. 

For simpler testing, I have prepared a code that can replicate this 

```
from mpire import WorkerPool
import numpy as np
from ase.build import bulk

class MyClass:
    def __init__(self):
        # Make a large atomic structure
        self.system = bulk('Al', 'fcc', a=4.05, cubic=True)
        self.system.repeat((4,4,4))
        
        # Make a list of 100 copies of the structure
        self.data = [self.system for _ in range(100)]
        ## Self.data = [Atoms_object, Atoms_object, ...]
        ## Atoms objects is a list of Atom objects
        ## Self.data = [[Atom_1_object, Atom_2_object, ...], [Atom_1_object, Atom_2_object, ...], ...]
    
    def time_consuming_function(self, x):
        # Gets the positions array of the atoms in the structure
        return x.get_positions()
    
    def run_1(self):
        self.results = []
        for x in self.data:
            self.results.append(self.time_consuming_function(x))
            
    def run_2(self):
        with WorkerPool(n_jobs=5) as pool:
            self.results = pool.map(self.time_consuming_function, self.data)

    def run_3(self):
        def task(data_index):
            return self.time_consuming_function(self.data[data_index])
        with WorkerPool(n_jobs=5) as pool:
            self.results = pool.map(task, range(len(self.data)))


z = MyClass()
z.run_1() # For-loop implementation
z.run_2() # MPIRE implementation
z.run_3() # MPIRE implementation + workaround
```

Thansk for the time. 

```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Exception: Exception occurred in Worker-0 with the following arguments:
Arg 0: Atom('Al', [0.0, 0.0, 0.0], index=0)
Arg 1: Atom('Al', [0.0, 2.025, 2.025], index=1)
Arg 2: Atom('Al', [2.025, 0.0, 2.025], index=2)
Arg 3: Atom('Al', [2.025, 2.025, 0.0], index=3)
Traceback (most recent call last):
  File "/home/krojas/apps/mambaforge/envs/pyagox/lib/python3.10/site-packages/mpire/worker.py", line 458, in _run_safely
    results = func()
  File "/home/krojas/apps/mambaforge/envs/pyagox/lib/python3.10/site-packages/mpire/worker.py", line 391, in _func
    _results = func(*args) if is_apply_func else func(args)
  File "/home/krojas/apps/mambaforge/envs/pyagox/lib/python3.10/site-packages/mpire/worker.py", line 571, in _helper_func_with_idx
    return args[0], self._call_func(func, args[1])
  File "/home/krojas/apps/mambaforge/envs/pyagox/lib/python3.10/site-packages/mpire/worker.py", line 596, in _call_func
    return func(*args, **kwargs)
TypeError: MyClass.time_consuming_function() takes 2 positional arguments but 5 were given
```

**Comment by sybrenjansen** [comment]
By default MPIRE unpacks iterables. In other words, the `map` is actually doing what starmap does in the vanilla `multiprocessing` package. See https://sybrenjansen.github.io/mpire/usage/map/map.html#circumvent-argument-unpacking for ways to avoid this behavior. 

Bottom-line: wrap your data with `mpire.utils.make_single_arguments` or use 
```
self.data = [(Atoms0,), (Atoms1,), (Atoms2,), (Atoms3,), ...]
```
