### ISSUE TITLE
Cannot call terminate on OSX with dill

### ISSUE THREAD

**Issue by dionhaefner** [sybrenjansen/mpire#94]
Example:

```python
import time
from mpire import WorkerPool

def proc_func():
    time.sleep(1)

if __name__ == "__main__":
    pool = WorkerPool(4, start_method="spawn", use_dill=True)
    pool.apply_async(proc_func)
    pool.terminate()
```

Traceback:

```bash
$ python crash.py
Traceback (most recent call last):
  File "/Users/dion/codes/prequod/crash.py", line 10, in <module>
    pool.terminate()
  File "/Users/dion/.virtualenvs/science/lib/python3.10/site-packages/mpire/pool.py", line 1035, in terminate
    self._worker_comms.drain_queues()
  File "/Users/dion/.virtualenvs/science/lib/python3.10/site-packages/mpire/comms.py", line 643, in drain_queues
    [self.drain_and_join_queue(q) for q in self._task_queues]
  File "/Users/dion/.virtualenvs/science/lib/python3.10/site-packages/mpire/comms.py", line 643, in <listcomp>
    [self.drain_and_join_queue(q) for q in self._task_queues]
  File "/Users/dion/.virtualenvs/science/lib/python3.10/site-packages/mpire/comms.py", line 660, in drain_and_join_queue
    process.start()
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/Users/dion/.virtualenvs/science/lib/python3.10/site-packages/multiprocess/queues.py", line 305, in __getstate__
    return Queue.__getstate__(self) + (self._cond, self._unfinished_tasks)
  File "/Users/dion/.virtualenvs/science/lib/python3.10/site-packages/multiprocess/queues.py", line 61, in __getstate__
    context.assert_spawning(self)
  File "/Users/dion/.virtualenvs/science/lib/python3.10/site-packages/multiprocess/context.py", line 373, in assert_spawning
    raise RuntimeError(
RuntimeError: JoinableQueue objects should only be shared between processes through inheritance
```

**Comment by sybrenjansen** [comment]
Unfortunately, up till now there's no macOs support yet. This issue has also been reported in https://github.com/sybrenjansen/mpire/issues/91 and there's an open PR that addresses this one issue. However, I cannot say everything will work after that one is merged, not until I get my hands on a mac or have set up a VM. I will try to do this in the near future.

**Comment by sybrenjansen** [comment]
This should already work on master, as I just tested it. But full macos support is coming soon, so stay tuned.
